# Generated by Django 3.2.3 on 2021-05-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('birth', models.DateField(verbose_name='Data de nascimento')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Grupo de atendimento')),
                ('min_age', models.IntegerField(verbose_name='Idade mínima')),
            ],
            options={
                'verbose_name': 'Grupo de atendimento',
                'verbose_name_plural': 'Grupos de atendimento',
                'ordering': ['-name', '-min_age'],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vacina')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VaccineLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=200, verbose_name='CNES')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('address', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('neighborhood', models.CharField(max_length=200, verbose_name='Bairro')),
                ('city', models.CharField(max_length=200, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Ponto de vacinação',
                'verbose_name_plural': 'Pontos de vacinação',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sala de vacinação')),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.vaccinelocation', verbose_name='Ponto de vacinação')),
            ],
            options={
                'verbose_name': 'Sala de vacinação',
                'verbose_name_plural': 'Salas de vacinação',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AvailableAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointment', models.DateField(verbose_name='Data')),
                ('time_appointment', models.TimeField(verbose_name='Horário')),
                ('id_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.vaccine', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'Agendamento disponível',
                'verbose_name_plural': 'Agendamentos disponíveis',
                'ordering': ['date_appointment', 'time_appointment'],
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Agendado'), ('C', 'Cancelado'), ('V', 'Vacinado')], default='A', max_length=1)),
                ('id_available', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.availableappointments', verbose_name='Agendamento escolhido')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.servicegroup', verbose_name='Grupo de atendimento')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='AppointmentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies', models.IntegerField(verbose_name='Número de vagas')),
                ('id_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.availableappointments', verbose_name='Agendamento disponível')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.vaccinationroom', verbose_name='Sala de vacinação')),
            ],
            options={
                'verbose_name': 'Quantidade de vagas para o agendamento',
                'verbose_name_plural': 'Quantidades de vagas para o agendamento',
            },
        ),
    ]
