# Generated by Django 3.2.3 on 2021-05-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinelocation',
            name='cnes',
            field=models.CharField(default=-1, max_length=200, verbose_name='CNES'),
            preserve_default=False,
        ),
    ]
