# Generated by Django 3.2.3 on 2021-05-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='staff',
        ),
    ]
