# Generated by Django 3.2.3 on 2021-05-30 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20210529_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='appointments',
            name='id_citizen',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.user', verbose_name='Cidadão'),
            preserve_default=False,
        ),
    ]
