# Generated by Django 3.2.3 on 2021-05-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20210528_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationroom',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Sala de vacinação'),
        ),
        migrations.CreateModel(
            name='AppointmentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies', models.IntegerField(verbose_name='Número de vagas')),
                ('id_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.availableappointments', verbose_name='Agendamento disponível')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.vaccinationroom', verbose_name='Sala de vacinação')),
            ],
            options={
                'verbose_name': 'Quantidade de vagas para o agendamento',
                'verbose_name_plural': 'Quantidades de vagas para o agendamento',
            },
        ),
    ]
