# Generated by Django 3.2.3 on 2021-05-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20210529_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth',
            new_name='date_birth',
        ),
    ]
