# Generated by Django 3.2.3 on 2021-05-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_rename_birth_user_date_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
