# Generated by Django 3.2.3 on 2021-05-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
