# Generated by Django 3.2.3 on 2021-06-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auto_20210531_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicegroup',
            options={'ordering': ['name', 'min_age'], 'verbose_name': 'Grupo de atendimento', 'verbose_name_plural': 'Grupos de atendimento'},
        ),
        migrations.RenameField(
            model_name='appointmentroom',
            old_name='id_appointment',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='appointmentroom',
            old_name='id_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='id_available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='id_citizen',
            new_name='citizen',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='id_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='availableappointments',
            old_name='id_vaccine',
            new_name='vaccine',
        ),
        migrations.RenameField(
            model_name='vaccinationroom',
            old_name='id_location',
            new_name='location',
        ),
    ]
