# Generated by Django 3.2.3 on 2021-06-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_auto_20210601_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='available',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentroom', verbose_name='Agendamento escolhido'),
        ),
    ]
