# Generated by Django 3.2.3 on 2021-06-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_appointments_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationroom',
            name='location',
        ),
        migrations.AddField(
            model_name='availableappointments',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.vaccinelocation', verbose_name='Local de vacinação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='available',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.availableappointments', verbose_name='Agendamento escolhido'),
        ),
        migrations.DeleteModel(
            name='AppointmentRoom',
        ),
        migrations.DeleteModel(
            name='VaccinationRoom',
        ),
    ]
