# Generated by Django 3.2.3 on 2021-06-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_auto_20210601_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableappointments',
            name='vacancies',
            field=models.IntegerField(default=0, verbose_name='Número de vagas'),
            preserve_default=False,
        ),
    ]
