# Generated by Django 3.2.3 on 2021-06-02 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_availableappointments_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do agendamento'),
            preserve_default=False,
        ),
    ]
