# Generated by Django 3.2.3 on 2021-06-03 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_appointments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='group',
        ),
        migrations.AddField(
            model_name='availableappointments',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.servicegroup', verbose_name='Grupo de atendimento'),
            preserve_default=False,
        ),
    ]
